name: 'Get Image Layer Size Difference'
description: 'Compare Docker image layer sizes between two releases to determine pull size differences.'
author: 'Furkan Tasbasi'
branding:
  icon: check-square
  color: blue
inputs:
  REPO_LIST:
    description: 'A space-separated list of repositories to compare.'
    required: true
  OLD_RELEASE:
    description: 'The old release/version to compare.'
    required: true
  NEW_RELEASE:
    description: 'The new release/version to compare.'
    required: true

outputs:
  difference:
    description: 'The size difference between old and new releases.'

runs:
  using: 'bash'
  main: 'entrypoint.sh'
