name: 'Get Image Layer Size Difference'
description: 'Compare Docker image layer sizes between two releases to determine pull size differences.'
author: 'Furkan Tasbasi'
branding:
  icon: anchor
  color: blue
inputs:
  repo_list:
    description: 'A space-separated list of repositories to compare.'
    required: true
  old_version:
    description: 'The old release/version to compare.'
    required: true
  new_version:
    description: 'The new release/version to compare.'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
